image: docker:20.10.6

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build jar
  - test
  - build and push docker image

before_script:
  # - source .${CI_COMMIT_REF_NAME}.env
  - echo "End CI/CD"

build:
  tags:
    - "local"
  image: maven:3.6.3-jdk-11-slim
  stage: build jar
  script:
    - mvn $MAVEN_CLI_OPTS -f chachkies/pom.xml package -DskipTests
  artifacts:
    paths:
      - chachkies/target/*.jar
    expire_in: 1 week
  only:
    - master

test:
  tags:
    - "local"
  image: maven:3.6.3-jdk-11-slim
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -f chachkies/pom.xml test
  only:
    - master


docker build:
  tags:
    - "local"
  image: docker:20.10.6-dind
  stage: build and push docker image
  # before_script:
    # - source .${CI_COMMIT_REF_NAME}.env
  script:
    - docker build chachkies --build-arg SPRING_ACTIVE_PROFILE=$SPRING_ACTIVE_PROFILE -t $DOCKER_REPO -f chachkies/Dockerfile
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD harbor-repo.vmware.com
    - docker push $DOCKER_REPO

after_script:
  - echo "End CI/CD"



